import { DEFAULT_DESIGN, type WatchDesign } from './types';

export interface Preset {
  id: string;
  label: string;
  emoji: string;
  design: WatchDesign;
}

const base = DEFAULT_DESIGN;

export const PRESETS: Preset[] = [
  {
    id: 'diver',
    label: 'Diver',
    emoji: '🌊',
    design: {
      ...base,
      model: 'Abyss Mariner',
      subLabel: 'AUTOMATIC · 300M',
      brandFont: 'jost',
      numeralFont: 'jost',
      logoMark: 'triangle',
      caseShape: 'round',
      caseMaterial: 'steel',
      caseMm: 42,
      caseFinish: 'brushed',
      lugStyle: 'tapered',
      lugWidthMm: 20,
      crownStyle: 'knurled',
      crownGuards: true,
      bezelStyle: 'dive',
      bezelColor: '#16243d',
      dialColor: '#101114',
      dialTexture: 'matte',
      minuteTrack: 'lines',
      indexStyle: 'dots',
      markerColor: 'lume',
      handStyle: 'sword',
      handColor: 'silver',
      lume: true,
      accentColor: '#3fc1c9',
      dateWindow: '3',
      strapType: 'rubber',
      strapColor: '#16181c',
      background: 'ocean',
    },
  },
  {
    id: 'dress',
    label: 'Dress',
    emoji: '🥂',
    design: {
      ...base,
      model: 'Vesper Sonnet',
      subLabel: 'SWISS MADE',
      brandFont: 'playfair',
      numeralFont: 'playfair',
      logoMark: 'diamond',
      caseShape: 'round',
      caseMaterial: 'gold',
      caseMm: 38,
      caseFinish: 'polished',
      lugStyle: 'straight',
      lugWidthMm: 18,
      crownStyle: 'cabochon',
      crownGuards: false,
      bezelStyle: 'smooth',
      bezelColor: '#16243d',
      dialColor: '#efe7d6',
      dialTexture: 'guilloche',
      minuteTrack: 'dots',
      indexStyle: 'roman',
      markerColor: 'black',
      handStyle: 'dauphine',
      handColor: 'gold',
      lume: false,
      accentColor: '#d4af5f',
      dateWindow: 'none',
      strapType: 'leather',
      leatherFinish: 'alligator',
      strapColor: '#16181c',
      background: 'blush',
    },
  },
  {
    id: 'pilot',
    label: 'Pilot',
    emoji: '✈️',
    design: {
      ...base,
      model: 'Echo Aviator',
      subLabel: 'FLIEGER',
      brandFont: 'oswald',
      numeralFont: 'oswald',
      logoMark: 'none',
      caseShape: 'round',
      caseMaterial: 'black',
      caseMm: 44,
      caseFinish: 'brushed',
      lugStyle: 'straight',
      lugWidthMm: 22,
      crownStyle: 'onion',
      crownGuards: false,
      bezelStyle: 'smooth',
      bezelColor: '#101114',
      dialColor: '#15161a',
      dialTexture: 'matte',
      minuteTrack: 'railroad',
      indexStyle: 'arabic',
      markerColor: 'white',
      handStyle: 'syringe',
      handColor: 'white',
      lume: true,
      accentColor: '#e8762c',
      dateWindow: 'none',
      strapType: 'leather',
      leatherFinish: 'grained',
      strapColor: '#6b4a2f',
      background: 'noir',
    },
  },
  {
    id: 'field',
    label: 'Field',
    emoji: '🧭',
    design: {
      ...base,
      model: 'Alpine Scout',
      subLabel: 'FIELD · 100M',
      brandFont: 'jost',
      numeralFont: 'jost',
      logoMark: 'none',
      caseShape: 'round',
      caseMaterial: 'titanium',
      caseMm: 38,
      caseFinish: 'matte',
      lugStyle: 'wire',
      lugWidthMm: 20,
      crownStyle: 'knurled',
      crownGuards: false,
      bezelStyle: 'none',
      bezelColor: '#101114',
      dialColor: '#5c5a3c',
      dialTexture: 'matte',
      minuteTrack: 'railroad',
      indexStyle: 'arabic',
      markerColor: 'white',
      handStyle: 'syringe',
      handColor: 'silver',
      lume: true,
      accentColor: '#e6d3a7',
      dateWindow: 'none',
      strapType: 'nato',
      strapColor: '#1f4d3a',
      background: 'sage',
    },
  },
  {
    id: 'racing',
    label: 'Racing',
    emoji: '🏁',
    design: {
      ...base,
      model: 'Podium Drift',
      subLabel: 'CHRONOMETER',
      brandFont: 'jost',
      numeralFont: 'jost',
      logoMark: 'circle',
      caseShape: 'round',
      caseMaterial: 'steel',
      caseMm: 40,
      caseFinish: 'mixed',
      lugStyle: 'twisted',
      lugWidthMm: 20,
      crownStyle: 'knurled',
      crownGuards: false,
      bezelStyle: 'tachymeter',
      bezelColor: '#101114',
      dialColor: '#f4f2ec',
      dialTexture: 'matte',
      minuteTrack: 'lines',
      indexStyle: 'baton',
      markerColor: 'black',
      handStyle: 'baton',
      handColor: 'black',
      lume: true,
      accentColor: '#d23b32',
      dateWindow: '6',
      strapType: 'leather',
      leatherFinish: 'rally',
      strapColor: '#283a55',
      background: 'paper',
    },
  },
  {
    id: 'minimal',
    label: 'Minimal',
    emoji: '◽',
    design: {
      ...base,
      model: 'Mono Cadence',
      subLabel: '',
      brandFont: 'jost',
      numeralFont: 'jost',
      logoMark: 'none',
      caseShape: 'round',
      caseMaterial: 'steel',
      caseMm: 39,
      caseFinish: 'polished',
      lugStyle: 'tapered',
      lugWidthMm: 20,
      crownStyle: 'knurled',
      crownGuards: false,
      bezelStyle: 'none',
      bezelColor: '#101114',
      dialColor: '#d7dade',
      dialTexture: 'matte',
      minuteTrack: 'none',
      indexStyle: 'minimal',
      markerColor: 'black',
      handStyle: 'baton',
      handColor: 'black',
      lume: false,
      accentColor: '#e6b13a',
      dateWindow: 'none',
      strapType: 'mesh',
      strapColor: '#7a7d82',
      background: 'paper',
    },
  },
  {
    id: 'regate',
    label: 'Sport-lux',
    emoji: '🛥️',
    design: {
      ...base,
      model: 'Riviera Régate',
      subLabel: 'AUTOMATIC',
      brandFont: 'marcellus',
      numeralFont: 'jost',
      logoMark: 'circle',
      caseShape: 'octagon',
      caseMaterial: 'steel',
      caseMm: 41,
      caseFinish: 'mixed',
      lugStyle: 'integrated',
      lugWidthMm: 22,
      crownStyle: 'knurled',
      crownGuards: false,
      bezelStyle: 'smooth',
      bezelColor: '#16243d',
      dialColor: '#16243d',
      dialTexture: 'linen',
      minuteTrack: 'lines',
      indexStyle: 'baton',
      markerColor: 'auto',
      handStyle: 'baton',
      handColor: 'silver',
      lume: true,
      accentColor: '#3fa9c9',
      dateWindow: '3',
      strapType: 'oyster',
      strapColor: '#7a7d82',
      background: 'slate',
    },
  },
  {
    id: 'stardust',
    label: 'Dreamy',
    emoji: '🌙',
    design: {
      ...base,
      model: 'Lunar Mirage',
      subLabel: 'CELESTIAL',
      brandFont: 'playfair',
      numeralFont: 'playfair',
      logoMark: 'star',
      caseShape: 'cushion',
      caseMaterial: 'rose',
      caseMm: 37,
      caseFinish: 'polished',
      lugStyle: 'twisted',
      lugWidthMm: 18,
      crownStyle: 'onion',
      crownGuards: false,
      bezelStyle: 'coin',
      bezelColor: '#3c2a55',
      dialColor: '#3c2a55',
      dialTexture: 'starry',
      minuteTrack: 'dots',
      indexStyle: 'mixed',
      markerColor: 'gold',
      handStyle: 'leaf',
      handColor: 'rose',
      lume: false,
      accentColor: '#e87ca0',
      dateWindow: 'none',
      strapType: 'leather',
      leatherFinish: 'smooth',
      strapColor: '#8f7fb0',
      background: 'noir',
    },
  },
];
